/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../index';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/common/src/localization';
import * as import4 from '../../youtube-player.service';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/i18n/tokens';
import * as import7 from '@angular/core/src/zone/ng_zone';
class YoutubePlayerModuleInjector extends import0.NgModuleInjector<import1.YoutubePlayerModule> {
  _CommonModule_0:import2.CommonModule;
  _YoutubePlayerModule_1:import1.YoutubePlayerModule;
  __NgLocalization_2:import3.NgLocaleLocalization;
  __YoutubePlayerService_3:import4.YoutubePlayerService;
  constructor(parent:import5.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import3.NgLocaleLocalization(this.parent.get(import6.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  get _YoutubePlayerService_3():import4.YoutubePlayerService {
    if ((this.__YoutubePlayerService_3 == null)) { (this.__YoutubePlayerService_3 = new import4.YoutubePlayerService(this.parent.get(import7.NgZone))); }
    return this.__YoutubePlayerService_3;
  }
  createInternal():import1.YoutubePlayerModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._YoutubePlayerModule_1 = new import1.YoutubePlayerModule();
    return this._YoutubePlayerModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.YoutubePlayerModule)) { return this._YoutubePlayerModule_1; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_2; }
    if ((token === import4.YoutubePlayerService)) { return this._YoutubePlayerService_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const YoutubePlayerModuleNgFactory:import0.NgModuleFactory<import1.YoutubePlayerModule> = new import0.NgModuleFactory(YoutubePlayerModuleInjector,import1.YoutubePlayerModule);